version: "3.9"
services:
  todo_list:
    container_name: todo_list
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'